a = input('digite algo: ')
print(' O tipó primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ',a.isalpha())
print('É alfanumérico? ',a.isalnum())
print('Está em maisúculas? ',a.isupper())
print('Está em minúsculas? ',a.islower())
print('Está captalizada? ',a.istitle())
